### PR TITLE
Update 100.15.0

### PR DESCRIPTION
**Pull request by zkline101**
cc: @saratchandrakarumuri

### CODE REVIEW

**Comment by dg0yal** [comment]
The website team is changing where the zips are hosted.
@saratchandrakarumuri do you have the URL to the new locations?

**Comment by zkline101** [comment]
Done, thank you.

**Comment by zkline101** [comment]
Updated to final and live URLs, please re-review.

**Review by dg0yal — APPROVED** [review]

**Review by saratchandrakarumuri — APPROVED** [review]

**Comment by zkline101** [comment]
Thank you both.

**Pull request merged**
